<?php
/**
 * Utility functions, and exposed Drupal Actions that perform Reddit tasks.
 */

/**
 * Implements hook_menu()
 * @return array of menu items
 */
function redditautomation_menu(){
	$items = array();
	$items ['admin/settings/redditautomation'] = array (
			'title' => t ( 'Configure Reddit Automation Tools' ),
			'description' => t ( 'Setup defaults for the Reddit Automation Tools' ),
			'page callback' => 'drupal_get_form',
			'page arguments' => array (
					'redditautomation_admin_form'
			),
			'access arguments' => array (
					'administer site configuration'
			)
	);

	return $items;
}


/**
 * Defines the exposed Actions
 * Implement hook_rules_action_info().
 *
 * http://www.drupalcontrib.org/api/drupal/contributions!rules!rules.api.php/function/hook_rules_action_info/7
 */
function redditautomation_rules_action_info() {
	return array (
	// Expose the Send Message function via Rules
			'redditautomation_send_message' => array (
					'label' => t ( 'Send Message' ),
					'group' => t ( 'Reddit' ),
					'parameter' => array (
							'username' => array (
									'type' => 'text',
									'label' => t ( 'Recipient' ),
									'description' => t ( 'The reddit username of the recipient.' )
							),
							'subject' => array (
									'type' => 'text',
									'label' => t ( 'Subject' ),
									'description' => t ( 'Subject of the Message.' )
							),
							'message' => array (
									'type' => 'text',
									'label' => t ( 'Message' ),
									'description' => t ( 'Full message you wish to send.' )
							)
					),

					'access callback' => array (
							'redditautomation_sending_access_callback'
					)
			),
			'redditautomation_send_bulk_message' => array (
					'label' => t ( 'Send Bulk Message' ),
					'group' => t ( 'Reddit' ),
					'parameter' => array (
							'recipients' => array (
									'type' => 'list<user>',
									'label' => t ( 'List of user\'s who should receive the message.' )
							),
							'subject' => array (
									'type' => 'text',
									'label' => t ( 'Subject' ),
									'description' => t ( 'Subject of the Bulk Message.' )
							),
							'message' => array (
									'type' => 'text',
									'label' => t ( 'Message' ),
									'description' => t ( 'Full message you wish to send to all in list.' )
							)
					),
					'access callback' => array (
							'redditautomation_sending_access_callback'
					)
			)
			// TODO: Add more functions, as they are completed.
	);
}

/**
 * Defines a few permissions for Reddit Automation Tasks.
 *
 * Implements hook_permission()]
 */
function redditautomation_permission() {
	return array (
			'redditautomation can send' => array (
					'title' => t ( 'Can send Reddit PM\'s' ),
					'description' => t ( 'Granted to members who are able to impersonate the Admin and send PM\'s on the site\'s behalf.' )
			),
			'redditautomation can post' => array (
					'title' => t ( 'Can post links/stories to Reddit' ),
					'description' => t ( 'Granted to members who are able to impersonate the Admin and post content to reddit on the site\'s behalf.' )
			)
	);
}

/**
 * Access callback for Rules Actions.
 * @return boolean
 */
function redditautomation_sending_access_callback() {
	return user_access ( 'redditautomation can send' );
}
/**
 * Access callback for Rules Actions.
 * @return boolean
 */
function redditautomation_posting_access_callback() {
	return user_access ( 'redditautomation can post' );
}


/**
 * Send a Reddit Message from the configured account to the $username.
 *
 * @param string $username
 * @param string $subject
 * @param string $message
 */
function redditautomation_send_message($username, $subject, $message) {
	$reddit = _redditautomation_get_reddit ();
	$reddit_usr = variable_get ( 'redditautomation_username', NULL );
	$reddit_pass = variable_get ( 'redditautomation_password', NULL );
	if (! is_null ( $reddit_usr ) && ! is_null ( $reddit_pass )) {
		$reddit->login ( $reddit_usr, $reddit_pass );
		$reddit_message = $reddit->sendMessage ( $username, $subject, $message );
	}
}

/**
 * Completely untried..
 *
 *
 * I'm assuming when you specify to Rules that you want a list<user>, that
 * it will spit out a list of User entities.. but I guess we'll have to try it and find out.
 *
 * @param array $userlist
 * @param string $subject
 * @param string $message
 */
function redditautomation_send_bulk_message($userlist, $subject, $message) {
	foreach ( $userlist as $user ) {
		redditautomation_send_bulk_message ( $user->name, $subject, $message );
	}
}

/**
 * Submit Post to Reddit.
 *
 * Action performed by administratively configured user account.
 *
 * @param string $subreddit
 * @param string $title
 * @param string $body
 * @return string either PostID
 * @throws Exception on any error.
 */
function redditautomation_submit_post($title, $body, $subreddit = null) {
	if (is_null ( $subreddit )) {
		$subreddit = variable_get ( 'redditautomation_default_subreddit', '' );
		if (! $subreddit) {
			throw new Exception ( "Unable to submit a post without a subreddit, either set one in the redditautomation admin screen, or pass one to this function." );
		}
	}
	if (! $title || ! $body) {
		throw new Exception ( "Empty title or body, unable to submit post." );
	}

	// Test user permissions?
	if (! user_access ( 'redditautomation can post' )) {
		// drupal_set_message('Access Denied','error');
		drupal_goto ();
	}

	$reddit = _reddit_automation_get_reddit ();

	// Make a request via their API, note the NULL as second parameter, that is for links only.
	$response = $reddit->createStory ( $title, NULL, $subreddit, $body );

	/* Find our new post and save the ID */
	sleep ( 2 );
	$l = $reddit->getListing ( $mainsubreddit, 5 );

	return _redditautomation_search ( $l->data->children, $title );
}

/**
 * Submit Post to Reddit.
 *
 * Action performed by administratively configured user account.
 *
 * @param string $subreddit
 * @param string $title
 * @param string $body
 * @return string either PostID
 * @throws Exception on any error.
 */
function redditautomation_submit_link($title, $link, $subreddit = null) {
	if (is_null ( $subreddit )) {
		$subreddit = variable_get ( 'redditautomation_default_subreddit', '' );
		if (! $subreddit) {
			throw new Exception ( "Unable to submit a link without a subreddit, either set one in the redditautomation admin screen, or pass one to this function." );
		}
	}
	if (! $title || ! $link) {
		throw new Exception ( "Empty title or link, unable to submit post." );
	}

	// Test user permissions?
	if (! user_access ( 'redditautomation can post' )) {
		// drupal_set_message('Access Denied','error');
		drupal_goto ();
	}

	$reddit = _reddit_automation_get_reddit ();

	// Make a request via their API, note the NULL as last parameter, that is for stories only.
	$response = $reddit->createStory ( $title, $link, $subreddit, NULL );

	/* Find our new post and save the ID */
	sleep ( 2 );
	$l = $reddit->getListing ( $mainsubreddit, 5 );

	return _redditautomation_search ( $l->data->children, $title );
}

/**
 * Submit Post to Reddit.
 *
 * Action performed by currently logged in user.
 *
 * @param string $subreddit
 * @param string $title
 * @param string $body
 * @return string either PostID
 * @throws Exception on any error.
 */
function redditautomation_submit_userpost($subreddit, $title, $body) {
	return 'Not currently Implemented.';

	$reddit = _reddit_automation_get_reddit ();

	$response = $reddit->createStory ( $title, NULL, $subreddit, $body );

	/* Find our new post and save the ID */
	sleep ( 2 );
	$l = $reddit->getListing ( $mainsubreddit, 5 );

	// Filter list by our user? Probably useful in busy sub..
	// $l->kind == 't3'; // Post!
	// $l->data->author == variable_get('redditautomation_username')
	return _redditautomation_search ( $l->data->children, $title );
}

/**
 * Submit a comment to a thread
 *
 * @param strig $post_id
 * @param string $comment_body
 * @return string $comment_id
 */
function redditautomation_post_comment($post_id, $comment_body) {
	if (! $post_id || ! $comment_body) {
		throw new Exception ( "Unable to post empty comment." );
	}
	$reddit = _redditautomation_get_reddit ();
	$reddit->addComment ( $post_id, $comment_body );
	//TODO: Fetch comment_id & return it.
}

/**
 * Search for comments
 * 
 * @param string $post_id
 * @param string $string (what to search for in title or body of comment)
 * @param int $depth (defaults to 1)
 * @param string $sr (Which subreddit to search, defaults to the administratively defined default, or reddit itself)
 * @return array (Either empty, or full of comment_id's)
 */
function redditautomation_fetch_comments($post_id, $string = null, $depth = 1, $sr = null) {
	$comments = array ();
	if (! $sr) {
		$sr = variable_get ( 'redditautomation_default_subreddit', 'reddit' );
	}
	$reddit = _redditautomation_get_reddit ();
	$j = $reddit->getcommentreplies ( $sr, $postID, $commentID );

	// Convert the response (object) into something parsable.. We want the Comment IDs.
	foreach ( $j ['data'] ['children'] as $c ) {
		// If we haven't specified a search, skip all the matching and just add them all
		// Otherwise, check the body first, then the title for a match.
		// Only store matches, if we specify a string.
		if (is_null ( $string ) || preg_match ( '/' . $string . '/i', $c ['data'] ['body'] ) || preg_match ( '/' . $string . '/i', $c ['data'] ['title'] )) {
			$comments [] = $c ['data'] ['name'];
		}
	}
	return $comments;
}

/**
 * Utility function, go through a list of posts, match the title against a known string, return that post's id.
 *
 * @param array $array
 * @param string $string
 */
function _redditautomation_search($array, $string) {
	foreach ( $array as $children ) {
		if ($children->data->title == $string)
			return $children->data->name;
	}
}
/**
 * Utility function, runs regex against comment body..
 * case insensitive.
 *
 * Example: "lyrics vote", would match: "lYrIcs votes" etc..
 *
 * @param array $array
 *        	of comments (result of a fetch_comments)
 * @param string $string
 * @return array of PostIDs for matching comments.
 */
function _redditautomation_commentsearch($array, $string) {
	$matches = array ();
	foreach ( $array as $children ) {
		if (preg_match ( '/' . $string . '/i', $children->data->body ))
			$matches [] = $children->data->name;
	}
	return $matches;
}

/**
 * Utility function, ensures only one copy of the Reddit Object is
 * instantiated at any one time.. for any user.. I suppose if two users
 * happened to be using this at the same time, it would work for both,
 * however, it is designed to run on the server, so, to all intents and purposes,
 * reddit wouldn't know it was two different people running the scripts.
 *
 * @throws Exception
 * @return reddit
 */
function _redditautomation_get_reddit() {
	static $reddit;

	if (! $reddit) {
		_redditautomation_load_api ();
		$u = variable_get ( 'redditautomation_username', '' );
		$p = variable_get ( 'redditautomation_password', '' );
		if (! $u || ! $p) {
			throw new Exception ( "Invalid Username/Password config for Reddit Automation module." );
		}
		$reddit = new reddit ( $u, $p );
	}
	return $reddit;
}

/**
 * Found this on the internet somewhere, to ensure the library code is loaded
 * and that we have the class available.
 */
function _redditautomation_load_api() {
	$lib_path = function_exists ( 'libraries_get_path' ) ? libraries_get_path ( 'redditapi' ) : 'sites/all/libraries/redditapi';
	$client = $lib_path . 'reddit.php';
	try {
		// Load the Client (once only)
		if (! class_exists ( 'reddit' ) && ! @include ($client)) {
			return NULL;
		}
		return TRUE;
	} catch ( Exception $e ) {
	}
	return FALSE;
}

/**
 * Begin the admin form for Reddit Automation Administration
 */
function redditautomation_admin_form($form,$form_state){
	$form['help'] = array(
		'#type' => 'markup',
			'#markup' => '<p>You need to set at least a site username & password, this
			should be a new account just for this site, to act as a "Robot".</p>',
	);
	$form['username'] = array(
			'#type' => 'textfield',
			'#default_value' => variable_get('redditautomation_username',''),
			'#title' => t('Reddit Username'),
			'#description' => t('A user account from reddit.com.'),
	);
	$form['password'] = array(
			'#type' => 'textfield',
			'#default_value' => variable_get('redditautomation_password',''),
			'#title' => t('Reddit Password'),
			'#description' => t('The password for that account.'),
	);
	$form['subreddit'] = array(
			'#type' => 'textfield',
			'#default_value' => variable_get('redditautomation_default_subreddit',''),
			'#title' => t("Default Subreddit"),
			'#description' => t('If you don\'t want to specify which subreddit for the functions/tools, add one here, and it will be used instead.'),
	);
	$form['submit'] = array(
			'#type' => 'submit',
			'#value' => t('Save'),
	);
	return $form;

}
/**
 * Save the settings.
 */
function redditautomation_admin_form_submit($form,$form_state){
	variable_set('redditautomation_username',$form_state['values']['username'];
	variable_set('redditautomation_password',$form_state['values']['password'];
	variable_set('redditautomation_default_subreddit',$form_state['values']['subreddit'];
}
